### ISSUE TITLE
Add max versions param for scan operation

### ISSUE THREAD

**Issue by Tolsi** [wbolster/happybase#101]

**Comment by wbolster** [comment]
your issue description is far from useful.

if you're talking about extra scan options, this is limited to what the thrift interface provides, which is https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/Hbase.thrift#L141-L154 so i don't think this can be done.

closing this issue; feel free to comment if you can come up with a better description.

**Comment by Tolsi** [comment]
Sorry for the bad description, I thought that everything is clear. I realized that it was a lack of thrift interface.
