### ISSUE TITLE
Can I use RandomRowFilter in table scan?

### ISSUE THREAD

**Issue by linetor** [wbolster/happybase#102]
I want to sample row key by using happybase with python 

So I write this code

for key, data in table.scan(filter='RandomRowFilter ( .11 )'):
    print key, data  # prints 'value1' and 'value

It prints thrift.Thrift.TApplicationException: Internal error processing scannerOpenWithScan

So I Chage

for key, data in table.scan(filter='RandomRowFilter ( ".11" )'):
    print key, data  # prints 'value1' and 'value

It still don't work...

Can't I use RandomRowFilter in table.scan(filterStr) in happybase?

**Comment by linetor** [comment]
Can I sample randomrowfilter by using happybase?

**Comment by wbolster** [comment]
specify a "filter" arg (as a string) for table.scan

On October 30, 2015 2:30:40 AM GMT+01:00, linetor <notifications@github.com> wrote:
>Can I sample randomrowfilter by using happybase?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/happybase/issues/102#issuecomment-152374653


    — Wouter

-- 
Sent from my phone. Please forgive my tpyos.

**Comment by linetor** [comment]
Thanks for your reply. But I wonder the I Can use randomrowfilter by happybase
In Java there are randomrowFilter( https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/RandomRowFilter.html )

But In this book there are no filter about randowmrowfilter ( http://hbase.apache.org/book.html#individualfiltersyntax )

So I Wonder I Can or Can't  use randomrowfilter by happybase 
And Itś reason is because of not support randomrowfilter in thrift server ??

**Comment by wbolster** [comment]
I have no idea. The string is sent as-is to the Thrift server. Happybase does _not_ have any specific support for any particular filter; it treats filters simply as strings.   So you should just try and if it doesn't work, that would be a HBase issue, not a Happybase issue.

**Comment by linetor** [comment]
Thanks for your reply
I will  checkth base api
I will close that issue
2015. 10. 30. 20:09에 "Wouter Bolsterlee" <notifications@github.com>님이 작성:
