### ISSUE TITLE
Nested columns documentation?

### ISSUE THREAD

**Issue by mamigot** [wbolster/happybase#103]
All of this is very helpful –thank you!

I wanted to ask, however, about the way in which nested columns could be implemented. I'm fairly new to HBase and to HappyBase and I can't figure out how to create nested entities e.g.:

![alt](https://camo.githubusercontent.com/91653116bc47bd9428a3620c58289f2553f352f5/687474703a2f2f696d6167652e736c696465736861726563646e2e636f6d2f356862617365736368656d616862617365636f6e323031322d3132303532353133303730372d70687061707030322f39352f6862617365636f6e2d323031322d68626173652d736368656d612d64657369676e2d69616e2d7661726c65792d73616c6573666f7263652d3134312d3732382e6a70673f63623d31333337393630343135)

(from ["HBaseCon 2012 | HBase Schema Design"](http://www.slideshare.net/cloudera/5-h-base-schemahbasecon2012))

I see that to add e.g. `col1` to the column family `cf`, I can do the following:
`table.put('row-key', {'cf:col1': 'value1'})`

to add a column family inside `col1`, should I just do the following?
`table.put('row-key', {'cf:col1': dict('nested_col_key', 'nested_col_value')})`

Thank you!!

**Comment by wbolster** [comment]
by only looking at the picture i think the idea is that you build your own strings for column qualifiers and values with the nested structure serialised inside. as far as happybase goes there is no direct support for this, so it's up to your code to provide right byte strings to store as column qualifiers and values.

**Comment by mamigot** [comment]
I see, @wbolster –thank you!!

**Comment by mamigot** [comment]
Hey @wbolster ,

This is what I was referring to (and what I wanted to confirm there's no direct support for, if that's the case):

```python
import happybase
con = happybase.Connection('localhost')
table = con.table('test')

# Column family is 'info', then there's 'market_cats' and a series of categories
# save 'ecommerce' and 'education' as categories
table.put('comp2', {'info:market_cats:ecommerce':str(True)})
table.put('comp2', {'info:market_cats:education':str(True)})

# Gets the items from the column family as expected
table.row('comp2', ['info'])
>> {'info:market_cats:ecommerce': 'True', 'info:market_cats:education': 'True'}

# Also as expected
table.row('comp2', ['info:market_cats:education'])
>> {'info:market_cats:education': 'True'}

# But what about stopping in the middle?
# (I'd like to see everything in "info:market_cats" here)
table.row('comp2', ['info:market_cats'])
>> {}
```

Is this what you mean is not supported? Thank you so much!

Best,

**Comment by wbolster** [comment]
As I understand it, what you are trying does not fit the data model offered by HBase. One approach would be to embed data into the row key, and use a prefix scan on the row key. Another approach would be to use (server side) scanner filters, which can do some matching on (partial) column names, but I'm not sure this approach would properly scale.

**Comment by mamigot** [comment]
Ah, I understand –and thank you for HappyBase! It's very clearly written and helpful.
