### ISSUE TITLE
How to get long long value of table?

### ISSUE THREAD

**Issue by wcc526** [wbolster/happybase#104]
put("key", {"cf": struct.pack(">q", 123456)})

how to get this value ?

I have try table.row("key")["cf"],but I can't get this value.

**Comment by wbolster** [comment]
it looks like you did not specify a proper combination of a column family and column qualifier ("column name"). see the documentation for lots of correct examples.


On December 4, 2015 6:50:22 AM GMT+01:00, chi-chi weng <notifications@github.com> wrote:
>put("key", {"cf": struct.pack(">q", 123456)})
>
>how to get this value ?
>
>I have try table.row("key")["cf"],but I can't get this value.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/happybase/issues/104


    — Wouter

-- 
Sent from my phone. Please forgive my tpyos.

**Comment by wcc526** [comment]
def batch_put_int(self, table_name, column, kv_list):
        table = self.connection.table(table_name)
        with table.batch() as b:
            for k, v in kv_list:
                b.put(k, {column: struct.pack(">q", v)})

    def get_int(table_name, column, row_key):
        table = self.connection.table(table_name)
        return struct.unpack(">q",table.row(row_key)[column])[0]

I have sovle this problem by unpack the return value.

I think @wbolster can add int value or long value support.

**Comment by wbolster** [comment]
No, HBase only stores byte string, and so does HappyBase. Designing the packing strategies for the pieces of data that form row keys, column names and column values is at the very core of designing a HBase data model for an application. Happybase is not a schema translator; it's more of a database driver.
