### ISSUE TITLE
How can I solve the 'KeyValue size too large' problem?

### ISSUE THREAD

**Issue by hoverzheng** [wbolster/happybase#105]
hello,all
I use happybase write data to hbase,My data size is 17M. And I got exception:
error: IllegalArgument(_message='KeyValue size too large')

And I changed the hbase-site.xml parameter:  
hbase.client.keyvalue.maxsize = 1G
But I didn't solve it.
What can I solve the problem?
thank you!!

**Comment by wbolster** [comment]
happybase itself doesn't limit anything, so this is happens somewhere at the hbase side. perhaps the thrift server has its own limits?

(btw, using huge keys/values is not comm

**Comment by hoverzheng** [comment]
thank you @wbolster. I solved it.
The thrift server configure had some problem. I changed the configure.
