### ISSUE TITLE
HappyBase vs Hbase JavaApi

### ISSUE THREAD

**Issue by ShAlex** [wbolster/happybase#106]
What is the best way to do multiple queries to hbase?

I write code in python 

```python

@staticmethod
def execute_query(key, table_name, con_pool):
        items = []
        with con_pool.connection() as connection:
            table = happybase.Table(table_name, connection)
            [row_start, row_end] = get_start_and_end_row(key)
            selected_rows = table.scan(row_start=row_start, row_stop=row_end)
            for key, data in selected_rows:
                items.append(Item(data))
        return items

@staticmethod
def execute_in_parallel(table_name, hbase_host, hbase_port, keys):
        pool = ThreadPool(24)
        con_pool = happybase.ConnectionPool(size=24, host=hbase_host, port=hbase_port)
        execute_query_partial = partial(execute_query, table_name=table_name, con_pool=con_pool)
        result_info = pool.map_async(execute_query_partial, keys, chunksize=1)
        result = result_info.get()
```

Also i have similar code in java api. 

In Java I get data from 100 keys in ~5 seconds, and in Python I get data from same 100 keys in ~50 seconds? 

Could you adviсe me anything? 

ps In java api there is a single connection for all keys scan.

**Comment by wbolster** [comment]
Few questions/remarks:

* What are you trying to achieve exactly? Run multiple scans in parallel, but why?
* What is the slow spot? Have you run this through an actual profiler (`cProfile` from the stdlib, e.g. using the `profilehooks` package) to see where time is spent? What is the slow factor? Network throughput? Individual region server performance?

(Also, I'm not sure what `ThreadPool` in your code refers to.)

**Comment by wbolster** [comment]
also i don't know what

> ps In java api there is a single connection for all keys scan.

means. You can use `table.scan()` to get a (lengthy) full table scan in Happybase.
