### ISSUE TITLE
is there a way to set a TTL(Time To Live) or Exipre in X seconds?

### ISSUE THREAD

**Issue by CheyenneForbes** [wbolster/happybase#110]

**Comment by wbolster** [comment]
i think the thrift interface does not offer this.

**Comment by johnseekins** [comment]
According to your own docs, you _can_ set a TTL at the table level:

http://happybase.readthedocs.io/en/stable/api.html#happybase.Connection.create_table

**Comment by johnseekins** [comment]
However, it doesn't appear to work. HBase column families expect the TTL argument to be just that: TTL.
Example from hbase shell help commands:
`hbase> create 't1', {NAME => 'f1', VERSIONS => 1, TTL => 2592000, BLOCKCACHE => true}`

In your docs, you (and thrift) appear to say we need to pass "timeToLive" to HBase for setting the TTL. This doesn't work.

**Comment by wbolster** [comment]
the `ColumnDescriptor` struct from the thrift api specifies it as a simple int:

```
  9:i32 timeToLive = -1
```

happybase does not alter or convert the value in any way when it gets information from hbase using the `.families()` call, so perhaps the thrift server or hbase core report wrong values?

**Comment by johnseekins** [comment]
Could be. I am running a rather ancient version of HBase (0.94)...
Let's assume that's the answer and the problem is solved, since the original question was just "can I set a TTL".
