### ISSUE TITLE
Need a robust connection & connection pool.

### ISSUE THREAD

**Issue by cherrot** [wbolster/happybase#112]
happybase currently use Thrift transport's `isOpen()` method (which is in fact the `TSocket` `isOpen()` method)  to determine [whether it should open a new connection or keep the current one](https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/connection.py#L164-L173). 

However, `isOpen()` only tells us whether you have closed this socket explicitly. (See [here](https://github.com/apache/thrift/blob/1fa273be5089070532908f159a0ccc38d7f7150c/lib/py/src/transport/TSocket.py#L44-L47) and [here](https://github.com/apache/thrift/blob/1fa273be5089070532908f159a0ccc38d7f7150c/lib/py/src/transport/TSocket.py#L72-L73) in thrift).

So, we should not use `isOpen` to determine whether we need a new connection. but to test the real socket object to see if the it is "dead" and should be closed.

Relative PR in thrift: https://github.com/apache/thrift/pull/945

**Comment by wbolster** [comment]
you changed your mind?

    — wouter

-- 
sent from my phone. please forgive my tpyos.

**Comment by cherrot** [comment]
Nope, instead I have pushed a new patch to `thrift` a few hours ago. I guess maybe it's better to reopen this issue after `thrift` has merged that?

**Comment by cherrot** [comment]
@wbolster  Should it be the `happybase`'s responsibility to tell the connection's state, or `thrift`'s? I need your opinion, please :)

**Comment by wbolster** [comment]
preferably lower level in the stack, so somewhere in a thrift library.

but note that happybase master is moving towards the `thriftpy` library which completely replaces usage of the `thrift` library.

**Comment by cherrot** [comment]
It seems that a `sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)` could solve most unhealthy connection problems. 

Maybe it's time to close this issue?
