### ISSUE TITLE
hey,guys! what's this situation?

### ISSUE THREAD

**Issue by wjwangjian** [wbolster/happybase#115]
`happybase.hbase.ttypes.IOError: IOError(_message='62115ms passed since the last invocation, timeout is currently set to 60000')`

**Comment by wbolster** [comment]
apparently your server is responding too slow according to your timeout settings.

**Comment by wjwangjian** [comment]
Thank you! where can i set the parameter of timeout? sorry, I know it looks stupid but i barely know HBase @wbolster

**Comment by wjwangjian** [comment]
`self.connection = happybase.Connection(address, compat='0.90', timeout=60000000000)`it‘s right? @wbolster

**Comment by wbolster** [comment]
it's either thrift in which case the happybase timeout applies. if it's inside hbase then there's nothing happybase can do (it's hbase config in that case).

**Comment by wjwangjian** [comment]
thank you so much! it's really helpful.
