### ISSUE TITLE
API to get only row keys

### ISSUE THREAD

**Issue by vskr** [wbolster/happybase#12]
Is there a way to get just the row keys (and don't get the column data) from hbase using happybase.

Usecase:
I am trying to implement pagination on rows. My row keys are random integers, they are unique but not sequential. 

The closest to efficient pagination I could think of is

a. Get all the row keys
b. Loop through row keys (in batch of 100) and get the column data, when needed

**Comment by kennyut** [comment]
( filter=b'KeyOnlyFilter() AND FirstKeyOnlyFilter()' ) 

works like a charm! 
Thank you wobloster!

**Comment by bhalgat20** [comment]
table.scan(filter=b'KeyOnlyFilter() AND FirstKeyOnlyFilter()')

This the most efficient I found till now. Thanks wbolster

**Comment by UmfintechWtc** [comment]
I use happyhbase but throw an exception：
  thriftpy2.transport.base.TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')

Here is the code：
  import happybase
  connection = happybase.Connection(host=host,port=9090)
  scan_filter = "RowFilter(RegexStringComparator, '^test')"
  Rec_Res = table.scan(filter=scan_filter,limit=2)

How can I solve this problem，ths；
