### ISSUE TITLE
Happybase with tornado sometimes throw 'TSocket read 0 bytes' error

### ISSUE THREAD

**Issue by shenzhun** [wbolster/happybase#123]
Hi,

I use happybase with HBase 1.2.0, it works. But when I use tornado with happybase, it throws 'TSocket read 0 bytes’ error sometimes.

my environment:
happybase=0.9
tornado=4.3
hbase=1.2.0

my demo code as below:
```
import happybase
pool = happybase.ConnectionPool(size=3, host='localhost')
def get_data(uid):
            with pool.connection() as conn:
                  table = conn.table('table_name')
                  response = dict(table.scan(row_prefix='{0},'.format(uid))).values()
```

**Comment by wbolster** [comment]
i don't know much about tornado, but my initial feeling is that tornado's async stuff does not play nicely with the threading.Queue implementation used by the happybase connection pool.

**Comment by Pils19** [comment]
Look at #130 i think it has something to do with hbase 1.2 ....

**Comment by cherrot** [comment]
Maybe this has nothing to do with tornado.  Check if your connection to HBase has gone away. Or you can switch to the git version of happybase, which relies on [thriftpy](https://github.com/eleme/thriftpy) and set `SO_KEEPALIVE` flag to the TCP socket by default.

For example in your `requirements.txt`: 
```
-e git+https://github.com/wbolster/happybase.git#egg=happybase
```

See also #112

**Comment by wbolster** [comment]
fyi: happybase 1.0.0 is out, and uses a different thrift implementation.

**Comment by shenzhun** [comment]
greate!

**Comment by shenzhun** [comment]
cool!
