### ISSUE TITLE
batch with timestamp set for each row

### ISSUE THREAD

**Issue by lilila** [wbolster/happybase#126]
Is there a way to use a batch instance with a specific timestamp for each row ? 
I can set up a specific timestamp using : 
`table.put('row-key', {'cf:col1': 'value1'}, timestamp=123456789)`
But when I try: 
```
b = table.batch()
b.put('row-key-1', {'cf:col1': 'value1', 'cf:col2': 'value2'},timestamp=123456789)
```
I get ` put() got an unexpected keyword argument 'timestamp'`

thanks

**Comment by wbolster** [comment]
unfortunately this is not possible since the thrift api does not support that.

you can specify a timestamp for the complete batch, though. see the user guide at
 https://happybase.readthedocs.io/en/latest/user.html#performing-batch-mutations

> While the methods on the Batch instance resemble the put() and delete() methods, they do not take a timestamp argument for each mutation. Instead, you can specify a single timestamp argument for the complete batch: […]

**Comment by rui-exe** [comment]
Man that would have been such a life saver
