### ISSUE TITLE
HappyBase multiple table scans

### ISSUE THREAD

**Issue by sauravbiswasiupr** [wbolster/happybase#127]
If i do multiple table scans  e.g --> 

from happybase import Connection
conn = Connection("localhost")
conn.open()

table = conn.table("test")
data = [list(table.scan()) for _ in range(100)]

I seem to get a TTransportException (Broken Pipe). What could be the possible reasons ?

**Comment by Pils19** [comment]
Which Version of Hbase and Python do you use, I sometimes have the same error and I also have this error #130 since i switched from hbase Version 0.94 to 1.2 ...

**Comment by wbolster** [comment]
i think the server side has issues in this case, unexpectedly closing the connection. not something happybase can do anything about i fear.

that said, can you try again and ensure the scan is CLOSED explicitly since relying on cpython refcounting might not be the best approach.

**Comment by sauravbiswasiupr** [comment]
@Pils19 , @wbolster yeah this is definitely some issue with Thrift Server protocol mismatches. Unfortunately I didn't get time to investigate the issue and rather went with the Java API for work.
