### ISSUE TITLE
Add callback to the Batch class when sending the batch

### ISSUE THREAD

**Issue by dsevilla** [wbolster/happybase#132]
It would be nice to have a callback parameter in the Batch class so that when the batch is sent to the server the callback is called, just for feedback. I've been working in sending lots of elements through batch and I have to implement myself a counter and a notification mechanism if you include the batch with `with`.

The syntax shouldn't be too disruptive. Just something along the lines of:

    with table.batch(batch_size=2000,callback=f) as b:

where the function `f` is already defined.

Other callbacks could be implemented, such as pre-send callback or post-sent callback.

Adding this should be no more than a handful of lines of code.

**Comment by wbolster** [comment]
i'm not sure happybase would be the place for that.

have you tried chunking your data and just sending smaller batches? the `batch_size` arg is for convenience anyway; it does not do anything special except for flushing every now and then. if you want extra logic i think the best place would be your application code.

also, there's already a debug log message every time the batch is sent to the server: https://github.com/wbolster/happybase/blob/master/happybase/batch.py#L57-L58 maybe that fits your use case already?

**Comment by wbolster** [comment]
i think this is an application concern, not a library concern. `batch_size` is just for convenience. adding features on top comes with complexity as well (e.g. what if the callback raises exceptions?).
