### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by myloginid** [wbolster/happybase#136]
[root@ggg-1 ~]# pip install --upgrade HappyBase
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already up-to-date: HappyBase in /usr/lib/python2.6/site-packages
Requirement already up-to-date: thriftpy>=0.3.8 in /usr/lib/python2.6/site-packages (from HappyBase)
Requirement already up-to-date: six in /usr/lib/python2.6/site-packages (from HappyBase)
Requirement already up-to-date: ply<4.0,>=3.4 in /usr/lib/python2.6/site-packages (from thriftpy>=0.3.8->HappyBase)
[root@ggg-1 ~]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import happybase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/happybase/__init__.py", line 14, in <module>
    from .connection import DEFAULT_HOST, DEFAULT_PORT, Connection  # noqa
  File "/usr/lib/python2.6/site-packages/happybase/connection.py", line 16, in <module>
    from .table import Table
  File "/usr/lib/python2.6/site-packages/happybase/table.py", line 25
    for name, cell in iteritems(cell_map)
      ^
SyntaxError: invalid syntax
>>>
[root@ggg-1 ~]# uname -a
Linux ggg-1.gce.com 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@ggg-1 ~]#

[root@ggg-1 ~]# python --version
Python 2.6.6

**Comment by myloginid** [comment]
Works on Python2.7

**Comment by majia29** [comment]
HappyBase 0.8

Release date: 2014-02-25

Add (and default to) ‘0.96’ compatibility mode in Connection.
Add support for retrieving sorted columns, which is possible with the HBase 0.96 Thrift API. This feature uses a new sorted_columns argument to Table.scan(). An OrderedDict implementation is required for this feature; with Python 2.7 this is available from the standard library, but for Python 2.6 a separate ordereddict package has to be installed from PyPI. (issue #39)

**Comment by wbolster** [comment]
use python 3 or maybe dead 2.7 if you must.

python 2.6 is completely end of life and i will not spend time maintaining compatibility for it.
