### ISSUE TITLE
TTransportException Error if key not Found

### ISSUE THREAD

**Issue by iammehrabalam** [wbolster/happybase#137]
Let say i have table **test** and it having rows with **key1**, **key2**

When i search multiple keys (i.e using **rows**), if key not found return **TTransportException**

if there any way to get only values of found keys in HBase table without error

Here is my code 

``` python
import happybase
pool = happybase.ConnectionPool(20, host='localhost', port=9090)

with pool.connection() as conn:
     t = conn.table('test')
     print t.rows(['key1','key2', 'key3'])
```

**Comment by wbolster** [comment]
this is not something that is under happybase's control unfortunately; this exception comes from the remote side (hbase thrift).

a scanner with `limit=1` (remember to check the row key if any is found!) could help.
