### ISSUE TITLE
Table flush

### ISSUE THREAD

**Issue by HariSekhon** [wbolster/happybase#139]
Hi,

Is it possible to add the capability to flush tables similar to HBaseAdmin flush? I'm not sure if that is exposed by the Thrift API as it's been a few years since I developed against it directly and I recall it wasn't the nicest - I've tried searching for docs just now but don't see any mention of this so I'm not sure it's possible through the Thrift API as the docs don't seem as thorough as the JavaDocs around this.

I've looked here in both these places in the official documentation but not sign of 'flush':

http://wiki.apache.org/hadoop/Hbase/ThriftApi

http://svn.apache.org/viewvc/hbase/trunk/hbase-thrift/src/main/resources/org/apache/hadoop/hbase/thrift/Hbase.thrift?view=markup

A second opinion on this is always a good thing in case I've missed something.

Thanks

Hari

**Comment by wbolster** [comment]
your analysis seems correct. if it's not in the thrift api, you're out of luck.
