### ISSUE TITLE
Happybase 1.0 syntax error on Python 2.6

### ISSUE THREAD

**Issue by HariSekhon** [wbolster/happybase#142]
My CI build for Python 2.6 breaks on Happybase 1.0 with the following:

```
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/happybase/__init__.py", line 14, in <module>
    from .connection import DEFAULT_HOST, DEFAULT_PORT, Connection  # noqa
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/happybase/connection.py", line 16, in <module>
    from .table import Table
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/happybase/table.py", line 25
    for name, cell in iteritems(cell_map)
      ^
SyntaxError: invalid syntax
```
I know Python 2.6 is old but I'd like to maintain compatibility as you never know what OS version people have when they download your tools and it's better for tools to be runnable on whichever servers you need where in real world production the OS versions may be out of your control.

**Comment by wbolster** [comment]
have you even *tried* reading the docs, especially the release notes, which are intended specifically for people upgrading, before bothering me with questions? your reasoning is not very reasonable. py 2.6 is completely end of life. releasing NEW software for such antique environments cannot be expected. especially since this is a volunteer run project. my time is valuable to me, I'm not using it to support your antique environments for you, for free.

**Comment by HariSekhon** [comment]
Yes I read the docs on several occasions to be able to use the library and I specifically checked the page http://happybase.readthedocs.io/en/latest/news.html before asking. I understand your perspective regarding older Python installations - I don't have any antique environments, all my stuff is free too, but you'll notice public CI systems still support Python 2.6 as well as 2.7 as it's not uncommon to encounter servers still on RHEL 6. It's for this reason that I try to keep compatibility where it's not too big an inconvenience. I coded around this yesterday, but thanks for your response anyway.

**Comment by wbolster** [comment]
i'm sorry for being harsh. this project turned into a bit of a maintenance hassle for me. nothing personal, it's just that keeping this project alive sometimes takes a too heavy toll. especially since most issue reports and emails i receive are actually support requests.

**Comment by HariSekhon** [comment]
I understand, I've found the same with the open source projects I've released, there's always something that needs updating or fixing for something else that updated, it never ends... too many lost evenings and weekends.

**Comment by wbolster** [comment]
anyway. is it just the dict comprehension that breaks compat? (not sure, don't have py26 installed)

**Comment by HariSekhon** [comment]
Sorry I've just realised I forgot to reply to this. So I did initially try fixing the code inline just to test but didn't finish as realized I'd actually previously added a downgrade workaround in the build scripts when I hit issues prior to raising this ticket so I went back to doing that because it's easier and safer to automate downgrading the version for users downloading my free tools and was a quicker fix.

What just reminded me of this ticket was the following blog post, which is a really good read and relates to what you were saying about Open Source both being a huge time drain as well as being an often thankless job:

http://www.snarky.ca/why-i-took-october-off-from-oss-volunteering

On this topic I'd like to take the time to say thank you very much for all your work on this library, it was very useful to me in a pinch as it allowed me to quickly write generic tools for random data generation and analysis to debug things like HBase data distributions when debugging performance and scaling, as well as write some active monitoring tools for Nagios compatible monitoring systems.

All of my tools are freely available for you to use if you should need have any similar needs in future. They can be found in my [PyTools](https://github.com/harisekhon/pytools) and [Advanced Nagios Plugins Collection](https://github.com/harisekhon/nagios-plugins) repos which I maintain regularly, so I very much appreciate all those countless worked nights and weekends spent on things like this.

Thank you very, very much :)
