### ISSUE TITLE
On Windows thrift files don't get picked up properly, combined issue with ThriftPY

### ISSUE THREAD

**Issue by ErKatz** [wbolster/happybase#148]
This is related to this issue in ThriftPY

On windows, I get the following error:
Traceback (most recent call last):
  File "C:/Users/Erez.Katz/PycharmProjects/UserSeg/GetData.py", line 1, in <module>
    import happybase
  File "C:\Users\Erez.Katz\UserSegmentation\lib\site-packages\happybase\__init__.py", line 11, in <module>
    'Hbase_thrift')
  File "C:\Users\Erez.Katz\UserSegmentation\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)
  File "C:\Users\Erez.Katz\UserSegmentation\lib\site-packages\thriftpy\parser\parser.py", line 499, in parse
    url_scheme))
thriftpy.parser.exc.ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'

'c' is recognized as the url scheme for the path 
'C:\\Users\\JLPicard\\UserSegmentation\\lib\\site-packages\\happybase\\Hbase.thrift'

This is also caused by this issue:
https://github.com/eleme/thriftpy/issues/269

My current workaround in the `happybase\\__init__.py`  and it is combined with the workaround suggested in https://github.com/eleme/thriftpy/issues/269 :

``
import platform

if platform.system()=="Windows":
   _thriftpy.load(
    'file://'+_pkg_resources.resource_filename('happybase', 'Hbase.thrift'),
    'Hbase_thrift')
else:
   _thriftpy.load(
    _pkg_resources.resource_filename('happybase', 'Hbase.thrift'),
    'Hbase_thrift')
``

The fix is localized to Windows only because ThriftPy currently does not handle the "file" scheme and just throws an exception when it encounters it.

**Comment by wbolster** [comment]
this seems something specific to `thriftpy` and hence out of scope for happybase.

**Comment by bhaskarbhuyan** [comment]
Modify the parser code in the windows side. Go to your python installation folder's site packages (...\Lib\site-packages\thriftpy\parser.py) and then make changes in line no. 488 where you get this line

    if url_scheme == '':
and change this to:
    if len(url_scheme) <= 1:
