### ISSUE TITLE
Connection timeout setting

### ISSUE THREAD

**Issue by vskr** [wbolster/happybase#15]
I was looking at happybase documentation here for Connection class  ( http://happybase.readthedocs.org/en/latest/api.html ), and was searching for timeout parameter but couldn't find one.

Is happybase.Connection() to a hbase thrift server a persistent connection. If not, does it have a default timeout ( does it fallback/use timeout defined in python thrift bindings) that can be changed.

**Comment by raman-hike** [comment]
How can I set other timeouts like rpc timeout, operation timeout

**Comment by aqiao** [comment]
> How can I set other timeouts like rpc timeout, operation timeout ?

Hi , any update on this?
