### ISSUE TITLE
thriftpy.thrift.TApplicationException:Invalid method name:'getTableNames'

### ISSUE THREAD

**Issue by hmhmj** [wbolster/happybase#150]
I use pip install the happybase, and use happybase connect the thrift2. However, when I use the conn.tables(), the exception "thriftpy.thrift.TApplicationException:Invalid method name:'getTableNames'" occured, so can anyone tell me how to solve the problem? Thanks very much.

**Comment by wbolster** [comment]
happybase does not use thrift2, but the normal "hbase thrift" interface.
