### ISSUE TITLE
context management on Connection()

### ISSUE THREAD

**Issue by DeoLeung** [wbolster/happybase#156]
Hi,

is there any plan to support context mangement on `Connection`? e.g
```python
import happybase as hb
with hb.Connection('localhost') as conn:
  # do something
```

may need to implement the `__enter__` and `__exit__` method

**Comment by wbolster** [comment]
reconnecting frequently is an anti-pattern so making that pattern easy by providing built-in support for it seems unwise.

if you really want to have a contex manager, you can easily make it yourself using something like this:

```python
import contextlib

@contextlib.contextmanager()
def my_connection(...):
    with contextlib.closing(happybase.Connection(...)) as connnection:
        yield connection
```

and use it like this:

```python
with my_connection() as c:
    c.tables()
```
