### ISSUE TITLE
Getting cybin.ProtocolError: No protocol version header error

### ISSUE THREAD

**Issue by phonchi** [wbolster/happybase#161]
My happybase version is 1.00 and hbase version is 1.21. According to the documentation, the connection can be established using the following commands

`connection = happybase.Connection('hostname')`

I have already start hbase thrift server using

`hbase thrift start`

and confirms that the 9090 port is listening by ThriftServer.

But I still getting following error when I execute `print(connection.tables())`

```
File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6400)
cybin.ProtocolError: No protocol version header
```

I think the default parameters port, transport should work for my environment describing above.

Any suggestion is appreciated!!

**Comment by wbolster** [comment]
usually errors like these are indeed caused by a wrong transport configuration.

do pre-1.0 happybase versions work? (different thrift library)

**Comment by phonchi** [comment]
After changing some setting in hbase-site.xml it works now!! I remove the following property:

```
<property>
  <name>hbase.regionserver.thrift.http</name>
  <value>true</value>
</property>
<property>
  <name>hbase.thrift.support.proxyuser</name>
  <value>true/value>
</property>
```

I am not sure whether these properties should be set or not. Anyway, thanks for your help!!

**Comment by wbolster** [comment]
great!
