### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by wlach** [wbolster/happybase#164]
Would it be possible to release a new version of this package? We're depending on some changes that are not in any released version for our python_moztelemetry package and it's causing problems:

https://bugzilla.mozilla.org/show_bug.cgi?id=1353032#c1

**Comment by wbolster** [comment]
sure.

i've just tagged and pushed 1.1.0 to pypi:

https://pypi.python.org/pypi/happybase/1.1.0

**Comment by wlach** [comment]
Woah, that was fast! Thank you

**Comment by wbolster** [comment]
fwiw, release notes at the usual place: https://happybase.readthedocs.io/en/latest/news.html
