### ISSUE TITLE
storing data in Hbase (Bytes conversion)

### ISSUE THREAD

**Issue by salvager** [wbolster/happybase#17]
Hi,

I have went through your documentation and right now stumbled up on storing data in Hbase. I have read that strings need to converted to ByteStrings before they are sent. 

I have did something like below but it keeps giving me IOError.

row = str("row")
col1 = str("col1")
value1 = str("value1")

table.put( row , {col1: value1})

Am i doing it right ? If i am wrong, can you please give me an example of doing this is 2.7 + version ?

Thanks

**Comment by sandeepsingh** [comment]
Hi i am getting this error, Please help me. 

happybase.hbase.ttypes.IOError: IOError(_message='org.apache.hadoop.hbase.NamespaceNotFoundException:  Crawler)

**Comment by wbolster** [comment]
that's unrelated, and lacks information. can't help you with that
