### ISSUE TITLE
How to return row's column version with timestamp great than given timestamp?

### ISSUE THREAD

**Issue by yungeo** [wbolster/happybase#170]
RT, I have the demand to scan the table and get the rows' column values with a timestamp  greater than the specified timestamp, while in hbase shell it can be achieved by “get 't1', 'r1', {TIMERANGE => [ts1, ts2]}” which given a timestamp range, but it seems that happybase not support that, how can I get the rows' column values with timestamp great than a given timestamp?

**Comment by wbolster** [comment]
thrift has limited support for this. you could try a time filter in a scanner.
