### ISSUE TITLE
Lots of `[Errno 32] Broken pipe` errors when using connection_pool

### ISSUE THREAD

**Issue by zhai3516** [wbolster/happybase#172]
Hi, I find a lot of `[Errno 32] Broken pipe` errors when i use the conn, getting from a connection_pool, to scan data in a table.
I discover that because scan operate would returns a generator, using connection_pool with it in a context manager would not happen a network access until i use the generator to fetch data. Exit the context manager, the conn will push back to pool. When i use the generator happen an error（such as TTransportException), this conn will not work, but it still in conn. Next time get this conn from pool will throw  `[Errno 32] Broken pipe` 

My demo code:
```python
conn_pool = None

def get_connetion_pool(timeout=2):
    global conn_pool
    if conn_pool is None:
        conn_pool = happybase.ConnectionPool(1)
    return conn_pool

def recent_events_v1(start, end, table, filter_str=None, limit=2000):
    with get_connetion_pool().connection() as conn:
            t = conn.table(table)
        start_row = 'ARTICLE' + str(start * 1000000)
        end_row = 'ARTICLE' + str(end * 1000000)
        return t.scan(row_start=start_row, row_stop=end_row, filter=filter_str, limit=limit)

def main():
    for i in range(5):
        try:
            filter_str = "SingleColumnValueFilter('basic', 'ArticleTypeID', =, 'binary:{value}')".format(value=struct.pack('>q', 52909257)) 
            # `52909257` this num in filter will result a  TTransportException error because its bytes contain a single quote.
            results = recent_events_v1(start=0, end=1505646570, table="test_article_java_2", filter_str=filter_str
            len([i for i in results]) 
        except:
            print traceback.format_exc()

```

**Comment by wbolster** [comment]
unless i am missing something, this is a bug in your code. as you noted, scans use generators, and will access the server when used. this means they can only be used while a connection is checked out from the pool.

i suggest something like this:

```python
scan = t.scan(...)
return list(scan)
```

to load the results inside the `with` block.
