### ISSUE TITLE
I have a problem “IOERROR”

### ISSUE THREAD

**Issue by Childdreams** [wbolster/happybase#177]
`Hbase_thrift.IOError: IOError(message='org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: IOException: 1 time, \n\tat org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.makeException(AsyncProcess.java:228)\n\tat org.apache.hadoop.hbase.client.AsyncProcess$BatchErrors.access$1700(AsyncProcess.java:208)\n\tat org.apache.hadoop.hbase.client.AsyncProcess.waitForAllPreviousOpsAndReset(AsyncProcess.java:1689)\n\tat org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:208)\n\tat org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:183)\n\tat org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1439)\n\tat org.apache.hadoop.hbase.client.HTable.put(HTable.java:1042)\n\tat org.apache.hadoop.hbase.thrift.ThriftServerRunner$HBaseHandler.mutateRowsTs(ThriftServerRunner.java:1329)\n\tat org.apache.hadoop.hbase.thrift.ThriftServerRunner$HBaseHandler.mutateRows(ThriftServerRunner.java:1275)\n\tat sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.hadoop.hbase.thrift.HbaseHandlerMetricsProxy.invoke(HbaseHandlerMetricsProxy.java:67)\n\tat com.sun.proxy.$Proxy11.mutateRows(Unknown Source)\n\tat org.apache.hadoop.hbase.thrift.generated.Hbase$Processor$mutateRows.getResult(Hbase.java:4386)\n\tat org.apache.hadoop.hbase.thrift.generated.Hbase$Processor$mutateRows.getResult(Hbase.java:4370)\n\tat org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)\n\tat org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)\n\tat org.apache.hadoop.hbase.thrift.TBoundedThreadPoolServer$ClientConnnection.run(TBoundedThreadPoolServer.java:289)\n\tat org.apache.hadoop.hbase.thrift.CallQueue$Call.run(CallQueue.java:64)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n')`

Native code is
```
connection = happybase.Connection('localhost',port=9099)
connection.open()
# print 'All tables: ',connection.tables(), '\n'
table = connection.table('daily_report')

print table.put('201710250015000', {'rmb:log_date': '10086','rmb:ex':'this is error'})

row = table.row(b'20171025001')
print row
# print(row[b'family:qual1'])  # prints 'value1'

# filter = "RowFilter(=,'substring:20171025')"

#FILTER=>"RowFilter(=,'substring:20171025')"

# for key, data in table.scan():
#     print key, data  # prints row key and data for each row\
connection.close()
```
I hope you can help me

**Comment by wbolster** [comment]
the problem is at the server side. this is a java stack trace, and not one caused by happybase.

**Comment by Childdreams** [comment]
ok thanks


243790881@qq.com
 
发件人： wouter bolsterlee
发送时间： 2017-10-26 13:51
收件人： wbolster/happybase
抄送： Childdreams; Manual
主题： Re: [wbolster/happybase] I have a problem “IOERROR” (#177)
the problem is at the server side. this is a java stack trace, and not one caused by happybase.
