### ISSUE TITLE
Supporting tornado?

### ISSUE THREAD

**Issue by ray1888** [wbolster/happybase#178]
i want  to ask have somebody use this library with tornado? because this library is based on thrift , and thrift is supporting tornado , so i want to use that with tornado to done the write data in hbase? it is possible?

**Comment by wbolster** [comment]
happybase itself has no supporting code for this. it seems `thriftpy` has some tornado support, but i doubt happybase will work without significant modifications.

**Comment by ray1888** [comment]
Reviewing my project , i think the part that i use happybase can using in multithreading instead of tornado coroutine , the problem isn't that confusing me.
