### ISSUE TITLE
Time Interval Based Flush

### ISSUE THREAD

**Issue by anandaverma** [wbolster/happybase#179]
Currently, happybase supports batch size flush. In my project, I had a requirement to add time interval based flush. And when both specified flush whichever met first.

I have it handy and running on prod. If this feature is desirable by others I would love to contribute back.

**Comment by wbolster** [comment]
hi, thanks for your contribution.

am i right in assuming you have some time based check somewhere in the batch api? tbh, i think this is not something that should go into happybase itself.

that might work for you, but is not a generic fix for everyboty. for instance, users might be expecting autoflush to happen in the background, which would require complex setups with threads and so on. that is certainly something i do not want to have in happybase.
