### ISSUE TITLE
Hbase connections are getting full when continuously the script using happybase is running, forcing me to restart hbase

### ISSUE THREAD

**Issue by safire007** [wbolster/happybase#181]
Hi,
I have a python script which connects to multiple tables in hbase using happybase to perform database operation and runs continuously. After ever 10 days the hbase connection pool gets full forcing me to restart hbase. I have used Connection.close() but still this issue persists. kindly help me in resolving this.

Thank You.

**Comment by wbolster** [comment]
this is not enough information. do you always return connections to the pool? what is ‘full’?

you cannot just dump unclear support requests without any code, behavious, stack traces, and so on in my bug tracker and assume other people wil pick those up for you.

you cannot expect free consultancy like this. it is very unreasonable to expect that.
