### ISSUE TITLE
failure on NO PROTOCOL VERSION ERROR

### ISSUE THREAD

**Issue by meirs84** [wbolster/happybase#188]
The most simple connection openning of all, most posts on this subject talk about openning the tcp connection from the same thread but here we have no threads and still thrift server returns a bad request as it seems in tcp dump
We are using kerberos is there a known problem i couldn't find information on? 
The funny thing it worked until we upgraded to the hortonworks 2.6,
any suggestions?

code:
![image](https://user-images.githubusercontent.com/7645922/36197532-ac988a5e-117c-11e8-93fb-d3f0f7bd830e.png)

stack trace:
![image](https://user-images.githubusercontent.com/7645922/36198092-4ce5f5ae-117e-11e8-985f-207629e92173.png)

**Comment by wbolster** [comment]
either a wrong `Connection(transport=...)` or something with kerberos+thriftpy. with the latter i have no experience, and it's also out of scope for `happybase` so check out the `thriftpy` project!
