### ISSUE TITLE
thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)

### ISSUE THREAD

**Issue by bruce-dev** [wbolster/happybase#189]
hi, all

when i run code below, it occurs: **thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)**. Does anyone have any idea? thx

code:
#!/usr/bin/python

import happybase

connection = happybase.Connection('10.16.20.58', port=9090, protocol='compact')
connection.open()
print(connection.tables())

**Comment by wbolster** [comment]
https://github.com/wbolster/happybase/search?q=TTransportException&type=Issues&utf8=%E2%9C%93
