### ISSUE TITLE
Connecting to Pseudo-distributed Hbase on AWS through Happybase.

### ISSUE THREAD

**Issue by SaiBhavanaAmbati** [wbolster/happybase#191]
I am new to hbase and I want to connect to a pseudo-distributed hbase running on AWS EC2 instance(Ubuntu) through a terminal, but the happybase connection command results in inaction . I have positively checked the accessibility of the aws instance by pinging it from the terminal. The hbase operations are working fine via hbase-shell on the aws-instance.

 
The command I have executed is as follows:
>>> import happybase
>>> co = happybase.Connection('34.220.155.118',9090)
                                                 (ip of AWS instance )
and I have to forcefully terminate due to inaction.Please suggest any possible means of changes in the configuration or commands for successful connection.The different ports we have also tried are 9000, 60000 and 9090  ,all resulting in the same inaction. 

Below is a screenshot of the hbase-site.xml 

![image](https://user-images.githubusercontent.com/19989302/40486273-71b41ffc-5f7e-11e8-99f1-660f3a2b2e3d.png)

**Comment by wbolster** [comment]
make sure you run the thrift daemon, that it's accessible from the outside, and that your transport type config (`transport` argument) matches.
