### ISSUE TITLE
Python2.6 issue while running happybase

### ISSUE THREAD

**Issue by anis016** [wbolster/happybase#194]
Hello!

from the [version history](http://happybase.readthedocs.io/en/latest/news.html#happybase-0-8) it seems happybase supports python2.6 however, when I ran a sample script there is an issue thrown from this function.

table.py
`
def make_row(cell_map, include_timestamp):
    """Make a row dict for a cell mapping like ttypes.TRowResult.columns."""
 return {
        name: (cell.value, cell.timestamp) if include_timestamp else cell.value
        for name, cell in iteritems(cell_map)
 }
`

It says that 
> Python2.6 does not support dictionary comprehension.

P.S: 
I just found this: https://github.com/wbolster/happybase/issues/142 
Never mind! I will look for other solutions. 

-Thanks

**Comment by wbolster** [comment]
the solution is to move away from python 2.6 since it is end-of-life technology.
