### ISSUE TITLE
TTransportException(type=4) 

### ISSUE THREAD

**Issue by nexemjail** [wbolster/happybase#197]
Hi, today i run into an issue using happybase of latest version 1.1.0 with hbase of 1.2.0

I run thrift like that `thrift start -c` and use `compact` parmeter to connect to 9090 port on my local running hbase.

thriftpy version is 0.3.9

After trying all possible combinations of parameters, I get one of these errors
`cybin.ProtocolError: No protocol version header`

`TTransportException(message='TSocket read 0 bytes', type=4)`

 or the error mentioned in title

I've read all the issues somehow connected with the error, but none of the answers helped me fix my problem.

Could you,please, give any advice? Am I doing something wrong?

Thanks.

**Comment by wbolster** [comment]
thrift vs thrift2?

**Comment by nexemjail** [comment]
Ive tried both without any success.

After that i swiched to low-level thrift python code via thrift2 protocol
