### ISSUE TITLE
How can I keep a long connection by using happybase ConnectionPool?

### ISSUE THREAD

**Issue by Atao19940194** [wbolster/happybase#200]
I try to use happybase in my django project, I want a long connection since the project was started.
but I found that the one pool's connection was very short, it just keep alive for few minutes, can you give me some ideas?

**Comment by wbolster** [comment]
not sure what this is about. the pool does not close connections itself.

**Comment by Atao19940194** [comment]
@wbolster thank you, i have solve this problem...  the problem happened when uwsgi close it's current thread and open a new thread
