### ISSUE TITLE
 ETL Flow using Happy base to ingest json

### ISSUE THREAD

**Issue by swaapnika** [wbolster/happybase#202]
My automated flow shoud be as below:

- parsing a file to get Json 

- write json to hbase 

By using happybase to ingest data in an automated way, I had to do a few things before writing.

- create hbase table, column family 

- flatten the incoming records to fit the syntax of put. 
`table.put(b’cf1:col1’, b’value’)`
 i.e., I have to iterate through the json and append the cf1:col to all values.I have 2 questions here.

- Is there a workaround instead of appending the cf:col to all values? since for very large json this gets expensive.

- In case there is a nested json, then how do I write using the put statement?
`table.put(b’cf1:col1:nestedkey’, b’nestedvalue’)`
(Do I still append the nested keys to the cf:col:nestedkey and add nestedval to it?)
How do I handle deeply nested jsons when I do it as above ?

**Comment by wbolster** [comment]
there is no single right data model. depends on your access pattern. even storing the json document as one big bytestring in a single cell may be viable.

since this is not happybase specific, i think you should research hbase modelling techniques.

re the omission of the column family: no, this is not possible. column families are a fundamental layer in the hbase sparse map model, and cannot be ignored.

**Comment by swaapnika** [comment]
Okay got it! All of this is access based.
If I understand it right, I can write a huge byte array for a column family like.what would be the Happybase put syntax. Can I avoid the col name and just write a huge byte array for a column family?
Like just the `columnfamily` Instead of `columnfamily:colname` ?
`table.put(b’columnfamily’, b’value)`

**Comment by wbolster** [comment]
not sure whether the empty string is a valid column name (just try it), otherwise just use `cf:data` or any other short fixed string.

if you're only ever reading back whole documents there is no need to split them, since that would only add overhead.
