### ISSUE TITLE
how to use batch size with connection pool

### ISSUE THREAD

**Issue by mathbugua** [wbolster/happybase#208]
My code  like this:
// main.py

```
pool = happybase.ConnectionPool(
        size=10,
        host="",
        port="",
    )
```
```
def write_data(data):
    with pool.connection(timeout=2) as conn:
        conn.table(cls.table_name).put(
            row=row_key,
            data=data,
            wal=False
        )
```

When the data comes, I  will write data to hbase by calling write_data. I will get a connection from conn pool, then write data. For this case, how to use batch_size args

**Comment by wbolster** [comment]
use the batch api

**Comment by sharepusher** [comment]
is that possible use batch together with connection pool, as there will be too many connections caused by batch operation and it's not so convenient to control the clients size with high QPS

**Comment by wbolster** [comment]
the pool gives you a normal connection, on which you can use a batch. since those concepts are not related, so there is no special way to "combine" them.

**Comment by sharepusher** [comment]
@wbolster Thanks for the clarification, I just mis-understand the document example, it is works.

**Comment by wbolster** [comment]
cool! 💐
