### ISSUE TITLE
Tsocket has read 0 bytes error

### ISSUE THREAD

**Issue by fedefel** [wbolster/happybase#211]
Hello,
I've a normal code that connects to an host with Hbase

```
connection = happybase.Connection(host,9090,protocol='compact',transport='buffered')
table = connection.table(table)
rows = table.scan(row_prefix = email)
for k,d in rows:
   print(k)
   print(d)
```
where on pycharm on my pc works fine (I can access this host, run Hbase shell without problems,querying data with no problems)
but when I put it on another host with Centos and make it run it gives 
```
File "/..../site-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)
```
or also doing  `print(list(rows)))` throws this error.
Why on local machine works without problem but on another host it gives this problems?

**Comment by wbolster** [comment]
different protocol or transport likely

**Comment by fedefel** [comment]
Sorry to disturb you, the error could be simple, but could you please give more example on how to fix it ?
How do I check on Thrift which protocol/transport mode he uses?

**Comment by wbolster** [comment]
sorry, i am not able to provide hbase setup troubleshooting advice here.

it seems the problem is not happybase code, but the setup/network.
