### ISSUE TITLE
Retrieve row using rowkey

### ISSUE THREAD

**Issue by swaapnika-guntaka** [wbolster/happybase#216]
I did a scan on my hbase table and copied the key. Using the same key when I try to fetch a row using table.row(key). It doesn't fetch any rows. Is there something I'm missing?

Hbase shell scan on a table
```
0005e42297264d4e9a90e5dbd7a97e42:2018-06-30:800aa0433b87d column=test_details: extra_msg, timestamp=1548406981629, value=exited-with-non-zero-status,ASSERTION,STACK_TRACE                                                            
 08f599917cc55ea420d
```

Happpybase command
`row = table.row(b'0005e42297264d4e9a90e5dbd7a97e42:2018-06-30:800aa0433b87d08f599917cc55ea420d', columns=columns)`

{}

**Comment by swaapnika-guntaka** [comment]
Since my key is an md5 has, I was able to fetch rows without having to convert to bytes.

row = table.row(0005e42297264d4e9a90e5dbd7a97e42:2018-06-30:800aa0433b87d08f599917cc55ea420d, columns=columns)

**Comment by wbolster** [comment]
you should always use byte strings. I suspect the problem is elsewhere
