### ISSUE TITLE
ThriftPy is deprecated

### ISSUE THREAD

**Issue by Terseus** [wbolster/happybase#221]
According to the [ThriftPy repository](https://github.com/Thriftpy/thriftpy), the project is deprecated.

[ThriftPy2](https://github.com/Thriftpy/thriftpy2) is the new replacement, and according to the [ThriftPy2 repo page](https://github.com/Thriftpy/thriftpy2#migrate-from-thriftpy), it's compatible with ThriftPy, so the migration should be easy.

Please note that [there are problems installing happybase in Python 3.7 for some users](https://github.com/wbolster/happybase/issues/209) and this should fix it.

**Comment by bwo** [comment]
it would be really great if a release could be cut to enable people to start using happybase on 3.7.

**Comment by wbolster** [comment]
happybase 1.2.0 is now on pypi:

- https://happybase.readthedocs.io/en/latest/news.html#happybase-1-2-0
- https://pypi.org/project/happybase/

thanks @bwo @Terseus
