### ISSUE TITLE
happybase with aws lambda.

### ISSUE THREAD

**Issue by wagnerbrodrigues** [wbolster/happybase#223]
I'm trying to use happybase, with aws lambda and emr.
when i submit my code, I get this error:
`
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'thriftpy2.transport.buffered.cybuffered'",
  "errorType": "Runtime.ImportModuleError"
}
`

my code:
`import json
import happybase

def lambda_handler(event, context):
    return json.dumps('ola')`

**Comment by wbolster** [comment]
the error clearly mentions thriftpy, not happybase
