### ISSUE TITLE
how to set host para with zookeeper?

### ISSUE THREAD

**Issue by universewill** [wbolster/happybase#230]
i got a zookeeper host with a ip list. How to set the host para to establish connection?

**Comment by wbolster** [comment]
not sure what you mean. happybase does not use zookeeper.

**Comment by universewill** [comment]
my peer give me a java demo to connect hbase:
<img width="652" alt="屏幕快照 2019-11-08 下午5 37 46" src="https://user-images.githubusercontent.com/6790730/68467349-fdfbd380-0250-11ea-92fa-d49ef1b13270.png">
<img width="534" alt="屏幕快照 2019-11-08 下午5 37 57" src="https://user-images.githubusercontent.com/6790730/68467352-ff2d0080-0250-11ea-8633-0d9c6d0892b4.png">

So how to connect the hbase with the  happybase.Connection function?

**Comment by wbolster** [comment]
this is not a support forum. seems you haven't read the documentation. tl;dr: run hbase thrift and connect to that.
