### ISSUE TITLE
AttributeError: 'DatabaseWrapper' object has no attribute 'table'

### ISSUE THREAD

**Issue by codeliger** [wbolster/happybase#231]
```
    self.device_table = connection.table('notify:device_table')
  File "/usr/local/lib/python2.7/dist-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'table'
```

why would I be getting an error saynig no table propery exists on the DatabaseWrapper. I am following the documentation.

**Comment by wbolster** [comment]
you did not explain what you're trying to do, and you did not show your code, but your stack trace shows django. this has nothing to do with happybase it seems

**Comment by codeliger** [comment]
this is the code `self.device_table = connection.table('notify:device_table')`

**Comment by wbolster** [comment]
unfortunately that doesn't tell anything. you still do not provide any context, as i hinted before, so if you want help you'll have to do a better job describing your issue before asking for other people's attention
