### ISSUE TITLE
Fetching a single timestamp in happybase

### ISSUE THREAD

**Issue by gautacharya** [wbolster/happybase#232]
Right now the _timestamp_ parameter for _[row](https://happybase.readthedocs.io/en/latest/api.html#happybase.Table.row)_ will return all values up to the specified version. Is there any way to return only the specified timestamp, as is possible in the Java API?

**Comment by wbolster** [comment]
unfortunately not. the thrift1 interface does not support that.

**Comment by gautacharya** [comment]
> unfortunately not. the thrift1 interface does not support that.

That's too bad. Can this be done in thrift2? Otherwise, would using the REST API be the alternative?

**Comment by wbolster** [comment]
perhaps, i have never looked into those
