### ISSUE TITLE
scan and batch.send fail while put and row succeed

### ISSUE THREAD

**Issue by saintthor** [wbolster/happybase#24]
need i do any configuration for hbase?

> > > import happybase as hb
> > > conn = hb.Connection( '10.8.210.182' )
> > > conn.tables()
> > > ['Recommendation', 'StatsResult', 'hbase_t1', 'test', 'total_score']
> > > t = conn.table( 'test' )
> > > t.scan()
> > > <generator object scan at 0x4e1a4b0>
> > > for x in t.scan(): print x
> > > ... 
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/python273/lib/python2.7/site-packages/happybase-0.4-py2.7.egg/happybase/api.py", line 567, in scan
> > >     scan_id = client.scannerOpenWithScan(self.name, scan)
> > >   File "/usr/local/python273/lib/python2.7/site-packages/happybase-0.4-py2.7.egg/happybase/hbase/Hbase.py", line 1716, in scannerOpenWithScan
> > >     return self.recv_scannerOpenWithScan()
> > >   File "/usr/local/python273/lib/python2.7/site-packages/happybase-0.4-py2.7.egg/happybase/hbase/Hbase.py", line 1733, in recv_scannerOpenWithScan
> > >     raise x
> > > thrift.Thrift.TApplicationException: Invalid method name: 'scannerOpenWithScan'

**Comment by xidongzhang** [comment]
I comacross the same questions my hbase version is 0.98
