### ISSUE TITLE
How to store Array / List / Dict/Struct to column of a Column Family

### ISSUE THREAD

**Issue by aj18** [wbolster/happybase#43]
I am trying to store and array to column of a columnfamily and get the following error 
TypeError: must be string or read-only character buffer, not list .

Work around i did was to convert it into string and the i was able to perform the put command .

However the challenge is when i create hive table referencing to hbase table and perform an explode functionality it treat my array as string and does not break it into multiple rows. The reason being i have converted array to string in my  put command.

Need some help or example to solve this issue.

Thanks in advance.

Anupam

**Comment by jeetu96** [comment]
Hi @wbolster 
I have a list of dictionaries like below,  and I am not not able to serialize it to bytestring and store in hbase.

value =  [
{ "name", "abc" , "type": "xyz" },
{ "name", "abc" , "type": "xyz" },
]

when I do value.encode('utf-8')  it throws an error 'list' object has no attribute 'encode' 
and when I do struct.pack("@P" , value )  it also throws an error 'list' object has no attribute 'encode' 


what I understand from the errors is that I need to do this :
value = b'[ { "name", "abc" , "type": "xyz" },{ "name", "abc" , "type": "xyz" }]'
and then struct.pack("@P" , value ) 

But it seems not good practice..

It would be helpful if you can give share your thoughts on this.

**Comment by wbolster** [comment]
you're commenting to a long closed issue from 2013. this is not helping.

that said, none of this has anything to do with happybase. serializing data into byte strings can be done in various ways. for instance, when using json, something like this could work `json.dumps(d).encode()`
