### ISSUE TITLE
table.row method can return unexpected data or TApplicationException 

### ISSUE THREAD

**Issue by ityaptin** [wbolster/happybase#60]
Hello, 

I'm face with happybase issue and don't understand a cause and any paths to resolve it. In our project we need to add or update many objects from array to hbase. 
For every object in array methods table.row and table.put are call in series. But sometimes, about every tenth request raise TApplicationException with text  http://pastebin.com/pEACuBxD or return unexpected data, i think from other table. For example in hbase shell get returns {'f:s_openstack': '"1"', 'f:source': '"openstack"'} but table.row returns http://pastebin.com/FHc8euv0       

I think issue with unexpected result may be caused by concurrency and time between send_getRowWithColumns and recv_getRowWithColumns, but all object processes are in single thread.  

Details:
Hbase is started in standalone mode.
Hbase and running code are placed at different hosts in one local network. 
Example of code https://github.com/openstack/ceilometer/blob/master/ceilometer/storage/impl_hbase.py#L312

**Comment by dpnova** [comment]
I'm also getting this issue. There's nothing in hbase, hdfs or thrift logs!

**Comment by dpnova** [comment]
FWIW retrying the request with a new connection from the pool seems to work fine. The connection must get into some kind of weird state...

**Comment by wbolster** [comment]
I can't reproduce / investigate this issue since almost no information is available about it, unfortunately...

**Comment by dpnova** [comment]
I'm a bit of a newcomer to using hbase like this, but I can do anything you need. 

fwiw I get similar errors for getScanner and scanWithScanner. 

What information can I provide to help diagnose? 

Cheers

On January 22, 2015 11:48:40 PM GMT+10:00, Wouter Bolsterlee <notifications@github.com> wrote:
>I can't reproduce / investigate this issue since almost no information
>is available about it, unfortunately...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/happybase/issues/60#issuecomment-71022145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wbolster** [comment]
logs, tracebacks, both client and server

David Novakovic <notifications@github.com> schreef op 22 januari 2015 14:50:55 CET:
>I'm a bit of a newcomer to using hbase like this, but I can do anything
>you need. 
>
>fwiw I get similar errors for getScanner and scanWithScanner. 
>
>What information can I provide to help diagnose? 
>
>Cheers
>
>On January 22, 2015 11:48:40 PM GMT+10:00, Wouter Bolsterlee
><notifications@github.com> wrote:
>>I can't reproduce / investigate this issue since almost no information
>>is available about it, unfortunately...
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/wbolster/happybase/issues/60#issuecomment-71022145
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/happybase/issues/60#issuecomment-71022428

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dpnova** [comment]
This can be closed, I've looked into the issue and there was unsafe thread usage in our client code.

if there's any fixes to be had here they should be documentation warnings regarding the use of scan/batch with connection pools.

Feel free to close...

Dank u wel!

**Comment by wbolster** [comment]
The warning here isn't good enough? :)  http://happybase.readthedocs.org/en/latest/user.html#obtaining-connections

**Comment by dpnova** [comment]
I had read that multiple times, but the generator returned from scan can make it too easy to exit the with block unsafely :p

I think this issue should help anyone who Googles the error though! 

On February 2, 2015 9:00:39 PM GMT+10:00, Wouter Bolsterlee <notifications@github.com> wrote:
>The warning here isn't good enough? :) 
>http://happybase.readthedocs.org/en/latest/user.html#obtaining-connections
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/happybase/issues/60#issuecomment-72439186

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wbolster** [comment]
Yeah, I agree it's a bit tricky.

A "safety net" that Happybase could provide would be to return a _wrapper_ around a real connection from the context manager (the `with` block), which only propagates the actual calls (such as `.row()`) on connections whose "lease" is still valid. But this is very error-prone and cumbersome, since this wrapping needs to propagate into the instances returned from `.table()`, `.batch()`, and `.scan()`. Not to mention the performance penalty.

**Comment by wbolster** [comment]
Btw, feel free to submit a PR for the docs that extends the current example about processing stuff outside the `with` block with a note about scans...
