### ISSUE TITLE
Question about setTimeRange

### ISSUE THREAD

**Issue by nshakhat** [wbolster/happybase#61]
Hi! I have a brief question but cannot find a place to write it. 
I need an ability to set time range during scanning. I didn't find this functionality in happybase now. Maybe I'm a bad researcher? If it's not the case, could you please evaluate how many efforts are required to enable this? I'm ready to contribute. Thrift API supports this AFAIK
P.S. Ceilometer OpenStack team :)

**Comment by rfyiamcool** [comment]
@manavkataria   thrift2 support timerange , but Maybe  happybase is not support Timerange Scan... 

╮(╯▽╰)╭
