### ISSUE TITLE
Problem with calling happybase functions inside spark map functions

### ISSUE THREAD

**Issue by thmour** [wbolster/happybase#80]
I've got my map function

```py
def map(doc_id):
    ....
    word_list = table.row(doc_id)
    ....

text_files.map(map).take(3)
```

and raises this error trying to pickle a dict maybe.
```
pickle.PicklingError: Can't pickle builtin <type 'method_descriptor'>
```

Is is something you can fix or the developers of spark?

**Comment by wbolster** [comment]
Can you show the results of both  `repr(table)` and `repr(doc_id`) ?

**Comment by thmour** [comment]
No I can't, the error is raised upon the function call, but I can assure you the doc_id is a unicode string

**Comment by wbolster** [comment]
The traceback on the linked page does *not* contain happybase at all, so I doubt that happybase is causing this.

Furthermore, happybase only handles byte strings not unicode instances, as outlined in the user guide: https://happybase.readthedocs.org/en/latest/user.html#manipulating-data

**Comment by thmour** [comment]
The error stack says it can't pickle method_descriptor, is the return type of `row()` just a `dict`? Do you return a custom class object with methods?

**Comment by wbolster** [comment]
It's a `dict`; you can check this for yourself using `print(repr(...))`. I'm still not convinced this issue has anything to do with Happybase though.

**Comment by thmour** [comment]
the problem lies in thrift api

**Comment by wbolster** [comment]
I still think the problems is something completely different. HappyBase only wraps a Thrift connection. Are you _absolutely_ sure you (or any of the libs you're using) are not serializing anything else then simple data structures?

Also, you're using `map` as a function name, but this is also a Python built-in function name. Perhaps some lib is trying to be smart about that as well, so it's probably better to use a custom function name.

**Comment by thmour** [comment]
Man, you didn't understand the last comment, it is not your fault. The problem is in thrift and spark and they should fix it sometime.

**Comment by wbolster** [comment]
Okay, that's what I though already. ;)
