### ISSUE TITLE
Option to scan table with partial row keys (wildcard support for table.scan)

### ISSUE THREAD

**Issue by charudut** [wbolster/happybase#83]
I was wondering if there is any option for me to do a table scan with only partial key information in hand. So, the way my tables are set up is, it has really long row keys (of the format [some_string, some_string, date_string_xxx]). in cases where I have to query information with partial key knowledge, how do I do it? I know there is row_prefix, but unfortunately in my case, the prefixes are constantly varying and only the date string will remain constant. So, basically, is there an option for me to do regex/wildcard sort of a query. I believe the answer is no, in that case what workaround would you suggest. It's always best to ask the author.

**Comment by wbolster** [comment]
HBase's storage model is optimized for sequential access of keys (keys are sorted internally). This means prefix searches are efficient, but anything that doesn't share a prefix will require a full table scan, which is prohibitively expensive for all but the smallest tables.

So, as you suggested yourself, the answer is "no" (except for a full table scan + filter), and the solution lies in using a row key design that matches your access patterns.

**Comment by charudut** [comment]
Hey wbolster, thank you for getting back on this. So, I'm gonna do a full table scan, and then filter out what I want. yeah, I figured that there needs some changes w.r.t row keys, that's a hint there!

**Comment by wbolster** [comment]
Yeah, but keep in mind that a full table scan will read *all* data on *all* machines in your cluster, so this will be extremely slow (lots of I/O).

**Comment by charudut** [comment]
oh yeah, tell me about it! I kinda figured that out in no time. because it was taking like 2 mins for two days worth of data. so now, my best option is to kinda of redesign the row key arrangement, so that i can make use of the 'row_prefix' feature. I had a question for you, is THRIFT/ REST the only way to talk to HBase table from an external client? Because one of my friend said, you could do it in Java. what I dint understand was, for implementing this in Java, don't you need these services too?

**Comment by wbolster** [comment]
If you do it in Java you will use different protocols than Thrift, and those protocols expose a bit more of HBase's internal API, but that won't solve the "table scans are slow" issue, which is fundamental to how HBase is designed (ordered sparse map, with ordering on row keys).

**Comment by charudut** [comment]
Ah. I see. While it may not solve my problem with entire table scan, I'm trying to play around with this implementation just to see if there is a way for me to do searches using partial keys. thanks for the tip wbolster!

**Comment by wbolster** [comment]
You also do filtering through Thrift, which in Happybase is exposed via `table.scan(filter='...')`. The result is that the filtering happen server-side, but it's still a full table scan.

**Comment by charudut** [comment]
okay, so that is doing a full table scan and then filtering from the results of the scan. do you think this is more efficient than doing a full table scan, and using Py regex do filtering. I have a feeling your approach might be faster..

**Comment by wbolster** [comment]
With server side filters (`table.scan(filter=...)`) the data doesn't have to be serialised -> sent over the wire (from java to python) -> unserialised -> filtered, so that's likely faster.   But it still doesn't scale.
