### ISSUE TITLE
client side flush

### ISSUE THREAD

**Issue by biskit** [wbolster/happybase#86]
hi, 
i'm seeing issues in scan where rows scanned before and updated (ie. delete/put) are returned again. not sure where it's happening and sometimes i get TypeError: unknown type TType etc...
this could be because WAL is not flushed? hbase does support client side flush, so it possible to add this to table object?
also, does setting wal=False do automatic flush?

**Comment by wbolster** [comment]
HappyBase just calls the Thrift API, propagating any flags like `wal` to the Thrift API, so it's up to the Thrift API, and outside Happybases' control to do something sensible with that flag. Happybase doesn't do any "smart things" under the hood.

The `TType` error you mentioned is weird; that suggests that a wrong Thrift call was issued. Do you have more information about that?

**Comment by biskit** [comment]
Hey Thanks for responding. I checked again after opening a request and figured out where the problem might be and there it was. I'm initializing a pool on a parent process and using it in a child process created via MultiProcessing.Process(). This does not like any shared objects that are native .so. 
I rewrote it to be a thread and let it run for a day and no issues so far. 
I use both psycopg2 and happybase and both invoke native libraries. Both have issues with sharing objects across processes.

**Comment by wbolster** [comment]
You cannot share objects across processes (after a `fork()`), especially when those objects refer to things like open file descriptors (network connections). The correct approach is to open connections in each child process. Assuming the "pool" you referred to is a `happybase.ConnectionPool`: yes, those are thread-safe, but not "fork-safe" (no such thing in my book).
