### ISSUE TITLE
hello, happybase support scan timestamp range

### ISSUE THREAD

**Issue by rfyiamcool** [wbolster/happybase#88]
hello, happybase support scan timestamp range ?

i can not find happybase doc abort timestamp range...   

tks  very much !!!

**Comment by wbolster** [comment]
Unfortunately the `Table.scan()` API is limited to what the Thrift interface offers, which is a single timestamp value (meaning "up to and including this point" i believe).

https://happybase.readthedocs.org/en/latest/api.html#happybase.Table.scan

**Comment by rfyiamcool** [comment]
yes  ,  Thank U
