### ISSUE TITLE
Q: Does HappyBase support aggregate operations?

### ISSUE THREAD

**Issue by mike20007** [wbolster/happybase#9]
Does happybase have support for aggregate functions like count(), sum() etc..?

Thanks

**Comment by dinesh1218** [comment]
@wbolster I have more than 2 lakh records in Hbase i need to get total count of that table, right now i'm going with `FirstKeyOnlyFilter() and KeyOnlyFilter()` but it gives me poor performance. Is there any way i could get the total count of an Hbase table? 
I'm using `Python3.5, Happybase 1.2.0`

**Comment by wbolster** [comment]
this is a hbase question, not happybase. but im afraid the answer is no...
