### ISSUE TITLE
set configuration options?

### ISSUE THREAD

**Issue by BurntSushi** [wbolster/happybase#90]
I'm a bit new to HBase, so I'm not sure if I've missed something, but is there a way to set client side config options with `happybase`? For example, I'd like to increase `hbase.client.keyvalue.maxsize`.

**Comment by wbolster** [comment]
I think these settings are for the Java-side HBase client. HappyBase uses the Thrift interface.

The Thrift server acts as a HBase client, and I don't think the Thrift server exposes any interface to set options on that HBase client.

**Comment by BurntSushi** [comment]
Darn, really? All righty, thanks!
