### ISSUE TITLE
Get only a limited number of columns 

### ISSUE THREAD

**Issue by savinay** [wbolster/happybase#93]
Is it possible to get only a limited number of columns for a column family from a row? Lets say I just want to fetch the first 10 values for ['cf1': 'col1']. Would be really grateful if someone helps me out here.

**Comment by savinay** [comment]
Hi all,

Can somebody help me with this problem please?

**Comment by wbolster** [comment]
I think the only way to do this is a scan with a server side filter. I think the one you're after is the `ColumnCountGetFilter`:

> ColumnCountGetFilter - takes one argument, a limit. It returns the first limit number of columns in the table.
> Syntax:  ColumnCountGetFilter (‘<limit>’)
> Example: ColumnCountGetFilter (4)

Source: http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/admin_hbase_filtering.html

With Happybase that would look like this (untested):

```python
for row_key, data in table.scan(columns=['cf1'], filter='ColumnCountGetFilter(10)'):
    print(row_key, data)
```

**Comment by savinay** [comment]
Thank you!! Helped me solve my problem.
