### ISSUE TITLE
Thrift API doesn't return time_to_live

### ISSUE THREAD

**Issue by dhermes** [wbolster/happybase#99]
When creating a table, the HBase shell returns

```
> describe 'test'
{NAME => 'cf2', ..., TTL =>'86400 SECONDS (1 DAY)' ...}
```

but when using

```python
table = connection.table('test')
table.families()
```

the `time_to_live` value returned in `2147483647` (This is the max value for int32.)

**Comment by dhermes** [comment]
FWIW I realize this likely isn't an issue in `happybase`, but was hoping you might know the source of the issue and / or some documentation about it.

**Comment by wbolster** [comment]
i guess it's a bug in the thrift server code (java, included in hbase sources)

**Comment by dhermes** [comment]
@wbolster Do you have a place that you've filed issues with the maintainers of `thrift`? https://github.com/apache/thrift doesn't have a way to file bugs

**Comment by wbolster** [comment]
hbase uses apache's jira instance at https://issues.apache.org/jira/browse/HBASE

**Comment by dhermes** [comment]
Thanks!
